### ISSUE TITLE
Carte Résultats Elections Présidentielles

### ISSUE THREAD

**Issue by jul-fls** [jul-fls/mspr-i1-eisi-bloc-3-g2-elections#2]

**Comment by sangmin-shim** [comment]
- [x] Trouver les données d'élection présidentielle (2012 ~ 2022) 
- [x] Trouver les données de coordonnées avec le bureau de votes
- [x] Visualiser les données (script) pour chaque année d'élection présidentielle
- [x] Récuperer les données d'origine via API (data.gouv.fr)
- [x] Faire un processus par AIRFLOW (Industrialisation)
